import pandas as pd
import matplotlib.pyplot as plt
matches=pd.read_csv("matches.csv")
deliveries=pd.read_csv("deliveries.csv")
print("1.",len(matches[matches["season"]==2008]))
city_counts=matches["city"].value_counts()
print("2. Maximum:",city_counts.idxmax(),city_counts.max())
print("Minimum:",city_counts.idxmin(),city_counts.min())
print("3.\n",city_counts)
print("4.\n",pd.crosstab(matches["toss_winner"],matches["toss_decision"]))
print("5.\n",matches["result"].value_counts()[["normal","tie"]])
print("6.\n",matches.loc[matches["result"]=="tie",["team1","team2","winner"]])
run_wins=matches[matches["win_by_runs"]>0]
print("7. Highest:\n",run_wins.loc[run_wins["win_by_runs"].idxmax()])
print("Lowest:\n",run_wins.loc[run_wins["win_by_runs"].idxmin()])
print("8.\n",matches["win_by_runs"].agg(["mean","median","std"]))
print("9. Highest venue:",run_wins.loc[run_wins["win_by_runs"].idxmax(),"venue"])
print("Lowest venue:",run_wins.loc[run_wins["win_by_runs"].idxmin(),"venue"])
pom=matches["player_of_match"].value_counts()
print("10.\n",pom[pom>3])
sixes=deliveries[deliveries["batsman_runs"]==6]
print("11. Number of sixes:",len(sixes))
print(sixes)
match_runs=deliveries.groupby("match_id")["total_runs"].sum().reset_index()
match_info=matches[["id","venue"]].rename(columns={"id":"match_id"})
match_runs=match_runs.merge(match_info,on="match_id")
print("12.\n",match_runs.groupby("venue")["total_runs"].mean())
umpires=matches[["umpire1","umpire2","umpire3"]].melt(value_name="umpire")["umpire"].dropna().value_counts()
print("13.\n",umpires[umpires==umpires.max()])
print("14.\n",matches["season"].value_counts().sort_index())
match_runs=deliveries.groupby("match_id")["total_runs"].sum().reset_index()
season_info=matches[["id","season"]].rename(columns={"id":"match_id"})
match_runs=match_runs.merge(season_info,on="match_id")
print("15.\n",match_runs.groupby("season")["total_runs"].sum())
runs=deliveries.groupby("batsman")["batsman_runs"].sum().sort_values(ascending=False)
print("16.\n",runs.head(10))
valid_wickets=deliveries[deliveries["player_dismissed"].notna()&~deliveries["dismissal_kind"].isin(["run out","retired hurt","obstructing the field"])]
print("17.\n",valid_wickets.groupby("bowler").size().sort_values(ascending=False))
outs=deliveries[deliveries["player_dismissed"].notna()].groupby("player_dismissed").size()
batting_average=runs.div(outs).dropna().sort_values(ascending=False)
print("18.\n",batting_average.head(10))
pd.crosstab(matches["season"],matches["toss_decision"]).plot(kind="bar")
plt.title("Toss Decisions Across All Seasons")
plt.xlabel("Season")
plt.ylabel("Number of Tosses")
plt.tight_layout()
plt.show()
played=pd.concat([matches["team1"],matches["team2"]]).value_counts()
wins=matches["winner"].value_counts()
team_stats=pd.DataFrame({"Total Matches":played,"Winning Matches":wins}).fillna(0)
team_stats["Win Rate (%)"]=team_stats["Winning Matches"]/team_stats["Total Matches"]*100
print("20.\n",team_stats)
team_stats[["Total Matches","Winning Matches"]].plot(kind="bar",figsize=(12,6))
plt.title("Total Matches vs Winning Matches")
plt.xlabel("Team")
plt.ylabel("Matches")
plt.xticks(rotation=75,ha="right")
plt.tight_layout()
plt.show()
winner_counts=matches["winner"].value_counts()
print("21.\n",winner_counts)
winner_counts.plot(kind="bar")
plt.title("Distribution of Winning Teams")
plt.xlabel("Team")
plt.ylabel("Wins")
plt.xticks(rotation=75,ha="right")
plt.tight_layout()
plt.show()
pd.crosstab(matches["toss_winner"],matches["toss_decision"]).plot(kind="bar",figsize=(10,5))
plt.title("Toss Outcomes of All Teams")
plt.xlabel("Team")
plt.ylabel("Number of Tosses")
plt.xticks(rotation=75,ha="right")
plt.tight_layout()
plt.show()
top5=winner_counts.head(5)
print("23.\n",top5)
top5.plot(kind="bar")
plt.title("Top 5 Teams With the Most Wins")
plt.xlabel("Team")
plt.ylabel("Wins")
plt.xticks(rotation=45,ha="right")
plt.tight_layout()
plt.show()