import pandas as pd
import matplotlib.pyplot as plt
matches=pd.read_csv("matches1.csv")
deliveries=pd.read_csv("deliveries1.csv")
print("1.",len(matches[matches["season"]==2008]))
city=matches["city"].value_counts()
print("2. Maximum:",city.idxmax(),city.max())
print("Minimum:",city.idxmin(),city.min())
print("3.",city)
print("4.",pd.crosstab(matches["toss_winner"],matches["toss_decision"]))
print("5.",matches["result"].value_counts())
print("6.",matches[matches["result"]=="tie"][["team1","team2","winner"]])
runs=matches[matches["win_by_runs"]>0]
print("7. Highest:",runs.loc[runs["win_by_runs"].idxmax()])
print("Lowest:",runs.loc[runs["win_by_runs"].idxmin()])
print("8.",matches["win_by_runs"].mean())
print("Median:",matches["win_by_runs"].median())
print("Standard deviation:",matches["win_by_runs"].std())
print("9. Highest:",runs.loc[runs["win_by_runs"].idxmax(),"venue"])
print("Lowest:",runs.loc[runs["win_by_runs"].idxmin(),"venue"])
pom=matches["player_of_match"].value_counts()
print("10.",pom[pom>3])
sixes=deliveries[deliveries["batsman_runs"]==6]
print("11.",sixes)
match_runs=deliveries.groupby("match_id")["total_runs"].sum()
venue=matches[["id","venue"]].rename(columns={"id":"match_id"})
match_runs=match_runs.reset_index().merge(venue,on="match_id")
print("12.",match_runs.groupby("venue")["total_runs"].mean())
umpires=matches[["umpire1","umpire2","umpire3"]].stack().value_counts()
print("13.",umpires.head(1))
print("14.",matches["season"].value_counts().sort_index())
season=matches[["id","season"]].rename(columns={"id":"match_id"})
season_runs=deliveries.groupby("match_id")["total_runs"].sum().reset_index()
season_runs=season_runs.merge(season,on="match_id")
print("15.",season_runs.groupby("season")["total_runs"].sum())
batsman=deliveries.groupby("batsman")["batsman_runs"].sum().sort_values(ascending=False)
print("16.",batsman.head(10))
wickets=deliveries[deliveries["player_dismissed"].notna()]
wickets=wickets[~wickets["dismissal_kind"].isin(["run out","retired hurt","obstructing the field"])]
print("17.",wickets.groupby("bowler").size().sort_values(ascending=False))
outs=deliveries[deliveries["player_dismissed"].notna()].groupby("player_dismissed").size()
average=batsman.div(outs).dropna().sort_values(ascending=False)
print("18.",average.head(10))
pd.crosstab(matches["season"],matches["toss_decision"]).plot(kind="bar")
plt.title("Toss Decisions Across Seasons")
plt.xlabel("Season")
plt.ylabel("Number of Tosses")
plt.show()
played=pd.concat([matches["team1"],matches["team2"]]).value_counts()
wins=matches["winner"].value_counts()
team=pd.DataFrame({"Total Matches":played,"Winning Matches":wins}).fillna(0)
team["Win Rate"]=team["Winning Matches"]/team["Total Matches"]*100
print("20.",team)
team[["Total Matches","Winning Matches"]].plot(kind="bar")
plt.title("Total Matches vs Winning Matches")
plt.xlabel("Team")
plt.ylabel("Matches")
plt.xticks(rotation=75)
plt.show()
winner=matches["winner"].value_counts()
print("21.",winner)
winner.plot(kind="bar")
plt.title("Distribution of Winning Teams")
plt.xlabel("Team")
plt.ylabel("Wins")
plt.xticks(rotation=75)
plt.show()
pd.crosstab(matches["toss_winner"],matches["toss_decision"]).plot(kind="bar")
plt.title("Toss Outcomes of All Teams")
plt.xlabel("Team")
plt.ylabel("Number of Tosses")
plt.xticks(rotation=75)
plt.show()
print("23.",winner.head(5))
winner.head(5).plot(kind="bar")
plt.title("Top 5 Teams With Most Wins")
plt.xlabel("Team")
plt.ylabel("Wins")
plt.show()

